### PR TITLE
Styling updates

### PR DESCRIPTION
**Pull request by 0xtemujin**
## What it solves

Resolves #

### CODE REVIEW

**Comment by zjesko** [comment]
image

Remove or fix pricing

**Comment by zjesko** [comment]
we don't have any prod or staging cwg, no need for this button
image

**Comment by zjesko** [comment]
Remove this `canto` box from nav bar, don't really need it and it looks off

image

**Comment by 0xtemujin** [comment]
These issues being tracked on https://linear.app/neobase/issue/CAN-129/cosmetic-fixes, https://linear.app/neobase/issue/CAN-130/token-pricing-is-off

**Pull request merged**
